server:
 port: 8080

mybatis:
 mapper-locations: # 所有的mapper映射文件
 - classpath:mapping/*.xml

spring:
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource # 配置当前要使用的数据源的操作类型
   driver-class-name: com.mysql.cj.jdbc.Driver # 配置MySQL的驱动程序类
   url: jdbc:mysql://localhost:3306/mars?serverTimezone=GMT%2B8 # 数据库连接地址
   username: mars # 数据库用户名
   password: mars # 数据库连接密码

 security:
   user:
      name: admin
      password: admin
      roles:
       - USER # 授权角色

logging:
  level:
    com.mars.mapper: debug
